#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/remotedesk/remotedesk /usr/bin/remotedesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/remotedesk.service ]; then
			rm /etc/systemd/system/remotedesk.service /usr/lib/systemd/system/remotedesk.service /usr/lib/systemd/user/remotedesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/remotedesk/files/systemd/remotedesk.service /usr/lib/systemd/system/remotedesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload remotedesk.service: Unit remotedesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/remotedesk.service:10: Executable path is not absolute: pkill -f "remotedesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/remotedesk.service
		fi
		systemctl daemon-reload
		systemctl enable remotedesk
		systemctl start remotedesk
	fi
fi
